- greeting:
    text_size: xl
    text: "Welcome to Blue Expert Tools"

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: long

# Optional: Shows server CPU/Memory usage
- resources:
    cpu: true
    memory: true
    disk: /
